USE GSSWEB
 

SELECT TOP(5) BLR.BOOK_ID, BOOK_NAME, COUNT(*) AS QTY
FROM BOOK_LEND_RECORD AS BLR 
LEFT JOIN BOOK_DATA AS BD
ON BLR.BOOK_ID = BD.BOOK_ID
GROUP BY BLR.BOOK_ID, BD.BOOK_ID, BD.BOOK_NAME
ORDER BY QTY DESC
