USE GSSWEB
GO

SELECT KEEPER_ID AS KeeperId, 
		USER_CNAME AS CName, 
		USER_ENAME AS EName, 
		YEAR(LEND_DATE) AS BorrowYear, 
		COUNT(*) AS BorrowCnt

FROM BOOK_LEND_RECORD AS BLR
LEFT JOIN MEMBER_M AS MM
ON BLR.KEEPER_ID = MM.[USER_ID]
GROUP BY KEEPER_ID, USER_CNAME, USER_ENAME, YEAR(LEND_DATE)
ORDER BY KEEPER_ID
